'use strict';
// 테스트 전용: 기존 설치된 Playwright를 NODE_PATH로 지정할 수 있습니다.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const root = path.resolve(__dirname,'..'), evidence = path.resolve(process.argv[3] || path.join(root,'..','risk-dashboard-qa-local'));
const C = require('../risk-core.js'), sample = require('../sample-data.js');
const key = 'robot-risk-dashboard.v1';
(async()=>{
  fs.mkdirSync(evidence,{recursive:true});
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
  const page = await context.newPage(), errors = [], requests = [], results = [];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
  page.on('console',m=>{if(m.type()==='error') errors.push(m.text());});
  page.on('request',r=>{if(/^https?:/.test(r.url()) && !(process.argv[2] && r.url().startsWith(process.argv[2]))) requests.push(r.url());});
  const check = (name,fn) => {fn();results.push(name);};
  const count = () => page.locator('#rows tr').count();
  const restore = async (risks,accept=true) => {
    const dialog = page.waitForEvent('dialog').then(d=>accept?d.accept():d.dismiss());
    await page.locator('#import-file').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:1,risks}))});
    await dialog;
    await page.waitForTimeout(100);
  };
  try {
    await page.goto(process.argv[2] || pathToFileURL(path.join(root,'index.html')).href);
    assert.equal(await count(),10); assert.equal(await page.locator('#metric-count').innerText(),'9');
    assert.equal(await page.locator('#metric-critical').innerText(),'2');
    assert.equal(await page.locator('#metric-average').innerText(),'11.1');
    const day = await page.evaluate(()=>RiskCore.today());
    assert.equal(await page.locator('#metric-overdue').innerText(),String(C.summary(sample,day).overdue));
    results.push('대상 URL 초기 로드 및 4개 KPI');
    await page.screenshot({path:path.join(evidence,'dashboard-desktop.png'),fullPage:true});
    await page.locator('#search').fill('핵심 센서'); assert.equal(await count(),1);
    await page.locator('#search').fill('존재하지않는항목'); assert.equal(await count(),0); assert.ok(await page.locator('#empty').isVisible());
    await page.locator('#clear').click();
    await page.locator('#level-filter').selectOption('3'); assert.equal(await count(),3);
    await page.locator('#status-filter').selectOption('active'); assert.equal(await count(),2);
    assert.equal(await page.locator('#metric-count').innerText(),'9');
    await page.locator('#clear').click(); await page.locator('#sort').selectOption('due');
    assert.equal(await page.locator('#rows tr').first().getAttribute('data-id'),'R-010');
    await page.getByRole('button',{name:'P5, I5, 25점 심각, 미종료 1건',exact:true}).click();
    assert.equal(await count(),1); assert.equal(await page.locator('#rows tr').getAttribute('data-id'),'R-002');
    await page.locator('#clear').click(); results.push('검색·빈 결과·등급/상태 필터·정렬·매트릭스 연계');
    await page.locator('#add').click();
    await page.locator('[name=title]').fill('취소할 항목'); await page.locator('#cancel').click(); assert.equal(await count(),10);
    await page.locator('#add').click();
    await page.locator('[name=title]').fill('<img src=x onerror=alert(1)> 테스트');
    await page.locator('[name=owner]').fill('테스트 담당'); await page.locator('[name=response]').fill('로컬 검증 계획');
    await page.locator('[name=probabilityPct]').fill('80.01'); await page.locator('[name=costImpact]').selectOption('5');
    assert.match(await page.locator('#score-preview').innerText(),/25 · 심각/);
    await page.locator('#editor').screenshot({path:path.join(evidence,'risk-editor.png')});
    await page.getByRole('button',{name:'저장',exact:true}).click(); assert.equal(await count(),11);
    assert.equal(await page.locator('#rows img').count(),0);
    await page.reload(); assert.equal(await count(),11); results.push('등록·취소·실시간 점수·입력 HTML 안전 표시·새로고침 저장');
    await page.getByRole('button',{name:'R-011 수정',exact:true}).click();
    await page.locator('[name=title]').fill('수정된 리스크'); await page.locator('[name=status]').selectOption('종료');
    await page.getByRole('button',{name:'저장',exact:true}).click();
    assert.equal(await page.locator('#metric-count').innerText(),'9');
    let dialog = page.waitForEvent('dialog').then(d=>d.dismiss()); await page.getByRole('button',{name:'R-011 삭제',exact:true}).click(); await dialog; assert.equal(await count(),11);
    dialog = page.waitForEvent('dialog').then(d=>d.accept()); await page.getByRole('button',{name:'R-011 삭제',exact:true}).click(); await dialog; await page.waitForTimeout(100); assert.equal(await count(),10);
    results.push('수정·종료 집계 갱신·삭제 취소/확인');
    const downloadPromise = page.waitForEvent('download'); await page.locator('#export').click(); const download = await downloadPromise;
    const downloaded = JSON.parse(fs.readFileSync(await download.path(),'utf8')); assert.deepEqual(C.validate(downloaded),sample);
    await restore([],false); assert.equal(await count(),10);
    await restore([]); assert.equal(await count(),0); assert.equal(await page.locator('#metric-average').innerText(),'—');
    await restore(downloaded.risks); assert.equal(await count(),10);
    await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});
    await page.waitForTimeout(100); assert.match(await page.locator('#message').innerText(),/복원 실패/); assert.equal(await count(),10);
    await page.locator('#import-file').setInputFiles({name:'duplicate.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:1,risks:[sample[0],sample[0]]}))});
    await page.waitForTimeout(100); assert.match(await page.locator('#message').innerText(),/중복/); assert.equal(await count(),10);
    await page.locator('#import-file').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(1024*1024+1)});
    await page.waitForTimeout(100); assert.match(await page.locator('#message').innerText(),/1MB/); assert.equal(await count(),10);
    results.push('전체 JSON 다운로드/왕복·복원 취소·0건·손상/중복/대용량 복원 거부');
    await page.reload();
    await page.setViewportSize({width:390,height:844}); await page.locator('#clear').click(); await page.evaluate(()=>window.scrollTo(0,0));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(evidence,'dashboard-mobile.png'),fullPage:true});
    await page.locator('#add').click(); assert.ok(await page.locator('#editor').isVisible());
    assert.ok(await page.evaluate(()=>document.querySelector('dialog').getBoundingClientRect().width<=innerWidth));
    await page.keyboard.press('Escape'); assert.equal(await page.locator('#editor').isVisible(),false);
    results.push('390px 모바일 가로 넘침 없음·모달·Escape 닫기');
    await page.setViewportSize({width:1440,height:1100});
    await page.evaluate(k=>localStorage.setItem(k,'corrupted'),key); await page.reload(); assert.equal(await count(),10);
    await page.getByRole('button',{name:'R-001 수정',exact:true}).click(); await page.locator('[name=title]').fill('손상 저장소 테스트'); await page.getByRole('button',{name:'저장',exact:true}).click();
    assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),'corrupted');
    assert.match(await page.locator('#storage-status').innerText(),/메모리 모드/);
    await restore(sample); assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).risks.length,10);
    await page.evaluate(()=>{Storage.prototype.setItem = function(){throw new DOMException('Quota exceeded','QuotaExceededError');};});
    await page.getByRole('button',{name:'R-001 수정',exact:true}).click(); await page.locator('[name=owner]').fill('저장 실패 검증'); await page.getByRole('button',{name:'저장',exact:true}).click();
    assert.match(await page.locator('#storage-status').innerText(),/저장 불가/); assert.equal(await count(),10);
    results.push('손상 저장본 덮어쓰기 방지·명시 복원·저장 실패 메모리 모드');
    await page.reload(); await page.locator('#add').click(); await page.locator('[name=title]').fill('   '); await page.locator('[name=owner]').fill('담당자'); await page.locator('[name=response]').fill('대응');
    await page.getByRole('button',{name:'저장',exact:true}).click(); assert.match(await page.locator('#form-error').innerText(),/title/); assert.equal(await count(),10);
    await page.locator('#cancel').click(); results.push('공백 필수값 저장 거부');
    await page.getByRole('link',{name:'계산 기준 보기',exact:true}).click(); assert.ok(await page.locator('#method').getAttribute('open') !== null);
    results.push('계산 기준 링크 클릭 시 설명 펼침');
    check('콘솔/페이지 오류 0건·외부 HTTP 요청 0건',()=>{assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);});
    fs.writeFileSync(path.join(evidence,'browser-results.json'),JSON.stringify({browser:await browser.version(),url:page.url(),desktop:[1440,1100],mobile:[390,844],testedAt:new Date().toISOString(),pass:results,errors,externalRequests:requests},null,2));
    console.log(JSON.stringify({passed:results.length,results,browser:await browser.version()},null,2));
  } finally {await browser.close();}
})().catch(err=>{console.error(err);process.exitCode=1;});
